/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 animated-human.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

export function AnimatedHuman(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/animated-human.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  console.log(actions)

  useEffect(() => {
    if (actions) {
      actions['SitDown'].setLoop(THREE.LoopOnce, 1);
      actions['SitDown'].clampWhenFinished = true;
      actions['SitDown'].reset();
      actions['SitDown'].play();

        setTimeout(() => {
          actions['StandUp'].setLoop(THREE.LoopOnce, 1);
          actions['StandUp'].clampWhenFinished = true;
          actions['StandUp'].reset();
          actions['StandUp'].play();
        }, 1000);
        setTimeout(() => {
          actions['WalkCycle'].setLoop(THREE.LoopRepeat);
          actions['WalkCycle'].play();
        }, 2000);

    }
  },[actions])
  return (
    <group ref={group} {...props} dispose={null} position={[0, 0.01, 0]}>
      <group name="Scene">
        <group name="metarig">
          <primitive object={nodes.spine} />
        </group>
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <skinnedMesh name="basic_human" geometry={nodes.basic_human.geometry} material={materials['default']} skeleton={nodes.basic_human.skeleton} />
        </group>
        <group name="WGT-rig_spine_fk" position={[0, 0.997, -0.015]} rotation={[1.823, 0, 0]} scale={0.131} />
        <group name="WGT-rig_spine_fk001" position={[0, 1.114, 0]} rotation={[1.694, 0, 0]} scale={0.118} />
        <group name="WGT-rig_spine_fk002" position={[0, 1.114, 0]} rotation={[1.539, 0, 0]} scale={0.149} />
        <group name="WGT-rig_spine_fk003" position={[0, 1.262, -0.005]} rotation={[1.542, 0, 0]} scale={0.166} />
        <group name="WGT-rig_tweak_spine" position={[0, 0.87, -0.048]} rotation={[1.823, 0, 0]} scale={0.066} />
        <group name="WGT-rig_tweak_spine001" position={[0, 0.997, -0.015]} rotation={[1.694, 0, 0]} scale={0.059} />
        <group name="WGT-rig_tweak_spine002" position={[0, 1.114, 0]} rotation={[1.539, 0, 0]} scale={0.074} />
        <group name="WGT-rig_tweak_spine003" position={[0, 1.262, -0.005]} rotation={[1.542, 0, 0]} scale={0.083} />
        <group name="WGT-rig_tweak_spine004" position={[0, 1.428, -0.01]} rotation={[1.948, 0, 0]} scale={0.028} />
        <group name="WGT-rig_torso" position={[0, 0.933, -0.031]} scale={0.338} />
        <group name="WGT-rig_hips" position={[0, 0.87, -0.048]} rotation={[1.823, 0, 0]} scale={0.141} />
        <group name="WGT-rig_chest" position={[0, 1.262, -0.005]} rotation={[1.542, 0, 0]} scale={0.188} />
        <group name="WGT-rig_shoulderL" position={[0.016, 1.383, 0.059]} rotation={[-0.001, -1.039, -0.001]} scale={0.151} />
        <group name="WGT-rig_upper_arm_parentL" position={[0.168, 1.365, -0.023]} rotation={[-1.354, -0.614, 2.844]} scale={0.069} />
        <group name="WGT-rig_upper_arm_fkL" position={[0.168, 1.365, -0.023]} rotation={[-1.354, -0.614, 2.844]} scale={0.276} />
        <group name="WGT-rig_forearm_fkL" position={[0.327, 1.145, -0.071]} rotation={[-1.712, -0.486, 2.655]} scale={0.226} />
        <group name="WGT-rig_hand_fkL" position={[0.433, 0.947, -0.043]} rotation={[-1.551, -0.115, 2.698]} scale={0.167} />
        <group name="WGT-rig_upper_arm_ikL" position={[0.168, 1.365, -0.023]} rotation={[-1.354, -0.614, 2.844]} scale={0.276} />
        <group name="WGT-rig_upper_arm_ik_targetL" position={[0.487, 1.268, -0.524]} rotation={[-2.876, 0.329, 1.785]} scale={0.062} />
        <group name="WGT-rig_hand_ikL" position={[0.433, 0.947, -0.043]} rotation={[-1.551, -0.115, 2.698]} scale={0.167} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleL" position={[0.327, 1.145, -0.071]} rotation={[Math.PI / 2, 0, -3.072]} scale={0.495} />
        <group name="WGT-rig_upper_arm_tweakL" position={[0.168, 1.365, -0.023]} rotation={[-1.354, -0.614, 2.844]} scale={0.069} />
        <group name="WGT-rig_upper_arm_tweakL001" position={[0.248, 1.255, -0.047]} rotation={[-1.354, -0.614, 2.844]} scale={0.069} />
        <group name="WGT-rig_forearm_tweakL" position={[0.327, 1.145, -0.071]} rotation={[-1.712, -0.486, 2.655]} scale={0.057} />
        <group name="WGT-rig_forearm_tweakL001" position={[0.38, 1.046, -0.057]} rotation={[-1.712, -0.486, 2.655]} scale={0.057} />
        <group name="WGT-rig_hand_tweakL" position={[0.433, 0.947, -0.043]} rotation={[-1.551, -0.115, 2.698]} scale={0.042} />
        <group name="WGT-rig_shoulderR" position={[-0.016, 1.383, 0.059]} rotation={[3.14, -1.039, -0.001]} scale={-0.151} />
        <group name="WGT-rig_upper_arm_parentR" position={[-0.168, 1.365, -0.023]} rotation={[1.788, -0.614, 2.844]} scale={-0.069} />
        <group name="WGT-rig_upper_arm_fkR" position={[-0.168, 1.365, -0.023]} rotation={[1.788, -0.614, 2.844]} scale={-0.276} />
        <group name="WGT-rig_forearm_fkR" position={[-0.327, 1.145, -0.071]} rotation={[1.429, -0.486, 2.655]} scale={-0.226} />
        <group name="WGT-rig_hand_fkR" position={[-0.433, 0.947, -0.043]} rotation={[1.591, -0.115, 2.698]} scale={-0.167} />
        <group name="WGT-rig_upper_arm_ikR" position={[-0.168, 1.365, -0.023]} rotation={[1.788, -0.614, 2.844]} scale={-0.276} />
        <group name="WGT-rig_upper_arm_ik_targetR" position={[-0.487, 1.268, -0.524]} rotation={[0.265, 0.329, 1.785]} scale={-0.062} />
        <group name="WGT-rig_hand_ikR" position={[-0.433, 0.947, -0.043]} rotation={[1.591, -0.115, 2.698]} scale={-0.167} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleR" position={[-0.327, 1.145, -0.071]} rotation={[-Math.PI / 2, 0, -3.072]} scale={-0.495} />
        <group name="WGT-rig_upper_arm_tweakR" position={[-0.168, 1.365, -0.023]} rotation={[1.788, -0.614, 2.844]} scale={-0.069} />
        <group name="WGT-rig_upper_arm_tweakR001" position={[-0.248, 1.255, -0.047]} rotation={[1.788, -0.614, 2.844]} scale={-0.069} />
        <group name="WGT-rig_forearm_tweakR" position={[-0.327, 1.145, -0.071]} rotation={[1.429, -0.486, 2.655]} scale={-0.057} />
        <group name="WGT-rig_forearm_tweakR001" position={[-0.38, 1.046, -0.057]} rotation={[1.429, -0.486, 2.655]} scale={-0.057} />
        <group name="WGT-rig_hand_tweakR" position={[-0.433, 0.947, -0.043]} rotation={[1.591, -0.115, 2.698]} scale={-0.042} />
        <group name="WGT-rig_neck" position={[0, 1.428, -0.01]} rotation={[1.856, 0, 0]} scale={0.11} />
        <group name="WGT-rig_head" position={[0, 1.534, 0.021]} rotation={[Math.PI / 2, 0, 0]} scale={0.171} />
        <group name="WGT-rig_tweak_spine005" position={[0, 1.481, 0.011]} rotation={[1.758, 0, 0]} scale={0.027} />
        <group name="WGT-rig_thigh_parentL" position={[0.084, 0.923, -0.011]} rotation={[-1.589, -0.132, 0.535]} scale={0.113} />
        <group name="WGT-rig_thigh_fkL" position={[0.084, 0.923, -0.011]} rotation={[-1.589, -0.132, 0.535]} scale={0.452} />
        <group name="WGT-rig_shin_fkL" position={[0.144, 0.475, -0.003]} rotation={[-1.376, -0.003, 0.549]} scale={0.406} />
        <group name="WGT-rig_foot_fkL" position={[0.145, 0.077, -0.081]} rotation={[-2.78, -0.034, 0.013]} scale={0.162} />
        <group name="WGT-rig_toe_fkL" position={[0.151, 0.02, 0.07]} rotation={[-2.725, -0.089, -3.127]} scale={0.064} />
        <group name="WGT-rig_thigh_ikL" position={[0.084, 0.923, -0.011]} rotation={[-1.589, -0.132, 0.535]} scale={0.452} />
        <group name="WGT-rig_thigh_ik_targetL" position={[0.584, 0.446, 0.726]} rotation={[0.04, 0.544, -0.011]} scale={0.106} />
        <group name="WGT-rig_foot_ikL" position={[0.145, 0.077, -0.081]} scale={0.162} />
        <group name="WGT-rig_VIS_thigh_ik_poleL" position={[0.144, 0.475, -0.003]} rotation={[Math.PI / 2, 0, 0.552]} scale={0.852} />
        <group name="WGT-rig_thigh_tweakL" position={[0.084, 0.923, -0.011]} rotation={[-1.589, -0.132, 0.535]} scale={0.113} />
        <group name="WGT-rig_thigh_tweakL001" position={[0.114, 0.699, -0.007]} rotation={[-1.589, -0.132, 0.535]} scale={0.113} />
        <group name="WGT-rig_shin_tweakL" position={[0.144, 0.475, -0.003]} rotation={[-1.376, -0.003, 0.549]} scale={0.101} />
        <group name="WGT-rig_shin_tweakL001" position={[0.145, 0.276, -0.042]} rotation={[-1.376, -0.003, 0.549]} scale={0.101} />
        <group name="WGT-rig_foot_tweakL" position={[0.145, 0.077, -0.081]} rotation={[-2.78, -0.034, 0.013]} scale={0.04} />
        <group name="WGT-rig_foot_spin_ikL" position={[0.151, 0.02, 0.07]} scale={0.081} />
        <group name="WGT-rig_foot_heel_ikL" position={[0.145, 0.077, -0.081]} scale={0.081} />
        <group name="WGT-rig_toe_ikL" position={[0.151, 0.02, 0.07]} rotation={[-2.725, -0.089, -3.127]} scale={0.064} />
        <group name="WGT-rig_thigh_parentR" position={[-0.084, 0.923, -0.011]} rotation={[1.553, -0.132, 0.535]} scale={-0.113} />
        <group name="WGT-rig_thigh_fkR" position={[-0.084, 0.923, -0.011]} rotation={[1.553, -0.132, 0.535]} scale={-0.452} />
        <group name="WGT-rig_shin_fkR" position={[-0.144, 0.475, -0.003]} rotation={[1.766, -0.003, 0.549]} scale={-0.406} />
        <group name="WGT-rig_foot_fkR" position={[-0.145, 0.077, -0.081]} rotation={[0.362, -0.034, 0.013]} scale={-0.162} />
        <group name="WGT-rig_toe_fkR" position={[-0.151, 0.02, 0.07]} rotation={[0.416, -0.089, -3.127]} scale={-0.064} />
        <group name="WGT-rig_thigh_ikR" position={[-0.084, 0.923, -0.011]} rotation={[1.553, -0.132, 0.535]} scale={-0.452} />
        <group name="WGT-rig_thigh_ik_targetR" position={[-0.584, 0.446, 0.726]} rotation={[-3.102, 0.544, -0.011]} scale={-0.106} />
        <group name="WGT-rig_foot_ikR" position={[-0.145, 0.077, -0.081]} rotation={[-Math.PI, 0, 0]} scale={-0.162} />
        <group name="WGT-rig_VIS_thigh_ik_poleR" position={[-0.144, 0.475, -0.003]} rotation={[-Math.PI / 2, 0, 0.552]} scale={-0.852} />
        <group name="WGT-rig_thigh_tweakR" position={[-0.084, 0.923, -0.011]} rotation={[1.553, -0.132, 0.535]} scale={-0.113} />
        <group name="WGT-rig_thigh_tweakR001" position={[-0.114, 0.699, -0.007]} rotation={[1.553, -0.132, 0.535]} scale={-0.113} />
        <group name="WGT-rig_shin_tweakR" position={[-0.144, 0.475, -0.003]} rotation={[1.766, -0.003, 0.549]} scale={-0.101} />
        <group name="WGT-rig_shin_tweakR001" position={[-0.145, 0.276, -0.042]} rotation={[1.766, -0.003, 0.549]} scale={-0.101} />
        <group name="WGT-rig_foot_tweakR" position={[-0.145, 0.077, -0.081]} rotation={[0.362, -0.034, 0.013]} scale={-0.04} />
        <group name="WGT-rig_foot_spin_ikR" position={[-0.151, 0.02, 0.07]} rotation={[-Math.PI, 0, 0]} scale={-0.081} />
        <group name="WGT-rig_foot_heel_ikR" position={[-0.145, 0.077, -0.081]} rotation={[-Math.PI, 0, 0]} scale={-0.081} />
        <group name="WGT-rig_toe_ikR" position={[-0.151, 0.02, 0.07]} rotation={[0.416, -0.089, -3.127]} scale={-0.064} />
        <group name="WGT-rig_root" scale={0.852} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/animated-human.glb')
