/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 human.gltf 
Author: abysmaljess (https://sketchfab.com/abysmaljess)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/standing-sitting-animation-09b82fda6ec54d06b740dfd56660b248
Title: Standing / Sitting Animation
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

export function Human(props) {
  const group = useRef()
  const { scene, animations } = useGLTF('./models/human.gltf')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  
  // Manually create animation mixer for the cloned scene
  const mixer = useMemo(() => {
    if (clone) {
      return new THREE.AnimationMixer(clone)
    }
    return null
  }, [clone])

  // Create actions from animations
  const actions = useMemo(() => {
    if (!mixer || !animations || animations.length === 0) return {}
    
    const actionsMap = {}
    animations.forEach((clip) => {
      const action = mixer.clipAction(clip)
      actionsMap[clip.name] = action
    })
    return actionsMap
  }, [mixer, animations])

  // Update mixer on each frame
  useFrame((state, delta) => {
    if (mixer) {
      mixer.update(delta)
    }
  })


  useEffect(() => {
    if (props.shouldStandUp && actions) {
      const actionKeys = Object.keys(actions)
      
      if (actionKeys.length > 0) {
        // Play the first animation (should be the standing animation)
        const animationName = actionKeys[0]
        const action = actions[animationName]
        if (action) {
          action.reset()
          action.setLoop(THREE.LoopOnce, 1)
          action.clampWhenFinished = true
          action.play()
        }
      }
    }
  }, [props.shouldStandUp, actions])

  return (
    <group ref={group} {...props} dispose={null} name="Human" >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a317dc88ec0043219d58cd8b06b6ff60fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Sit_Arm" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_31">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_254" position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_255" geometry={nodes.Object_255.geometry} material={materials['Material.005']} skeleton={nodes.Object_255.skeleton} />
                  </group>
                </group>
                <group name="cs_grp" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="cs_master" position={[0.5, 0, 17.5]} scale={0.1} />
                  <group name="cs_square_2" position={[0.5, 0, 1.497]} rotation={[-Math.PI, 0, 0]} scale={0.154} />
                  <group name="cs_square" position={[1.5, 0, 1.497]} rotation={[-Math.PI, 0, 0]} scale={0.154} />
                  <group name="cs_hips" position={[0.5, 0, 11.5]} scale={0.206} />
                  <group name="cs_circle" position={[0.5, 0, 4.5]} scale={0.206} />
                  <group name="cs_neck" position={[0.5, 0, 14.5]} scale={0.206} />
                  <group name="cs_head" position={[0.5, 0, 13.5]} scale={0.206} />
                  <group name="cs_shoulder_left" position={[0.5, 0, 15.5]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={1.038} />
                  <group name="cs_arm_fk" position={[1.5, 0, 8.5]} scale={0.822} />
                  <group name="cs_forearm_fk" position={[2.5, 0, 8.5]} scale={0.822} />
                  <group name="cs_sphere_012" position={[3.5, 0, 2.5]} scale={0.206} />
                  <group name="cs_sphere" position={[0.5, 0, 2.5]} scale={0.206} />
                  <group name="cs_hand" position={[0.5, 0, 19.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_circle_025" position={[2.5, 0, 4.5]} scale={0.206} />
                  <group name="cs_circle001" position={[0.5, 0, 4.5]} scale={0.206} />
                  <group name="cs_shoulder_right" position={[0.5, 0, 16.5]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={1.038} />
                  <group name="cs_thigh_fk" position={[0.5, 0, 7.5]} scale={0.822} />
                  <group name="cs_calf_fk" position={[0.5, 0, 8.5]} scale={0.822} />
                  <group name="cs_foot" position={[0.5, 0, 10.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_foot_roll" position={[0.5, 0, 12.5]} scale={0.592} />
                  <group name="cs_foot001" position={[0.5, 0, 10.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_foot_01" position={[0.5, 0, 18.5]} rotation={[0, 0, Math.PI / 2]} scale={2.186} />
                  <group name="cs_foot002" position={[0.5, 0, 10.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_toe" position={[0.5, 0, 9.5]} scale={0.429} />
                  <group name="cs_user_Ctrl_Hand_IK_Right" position={[-0.195, -0.284, 0.646]} rotation={[2.998, 0.011, -0.867]} scale={0.096} />
                </group>
                <group name="meHumanMale001" position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/human.gltf')
