/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 human.gltf 
Author: abysmaljess (https://sketchfab.com/abysmaljess)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/standing-sitting-animation-09b82fda6ec54d06b740dfd56660b248
Title: Standing / Sitting Animation
*/

import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

// Helper function for smooth interpolation
const lerp = (start, end, t) => {
  return start + (end - start) * t
}

// Helper function to clamp value between min and max
const clamp = (value, min, max) => {
  return Math.max(min, Math.min(max, value))
}

// Easing functions for more natural motion
const easeInOutCubic = (t) => {
  return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2
}

const easeOutElastic = (t) => {
  const c4 = (2 * Math.PI) / 3
  return t === 0 ? 0 : t === 1 ? 1 : Math.pow(2, -10 * t) * Math.sin((t * 10 - 0.75) * c4) + 1
}

const easeInOutQuad = (t) => {
  return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2
}

// Calculate responsive target position based on screen width
const getTargetPosition = () => {
  if (typeof window === 'undefined') return { x: 3.5, y: 0, z: -1 }
  
  const width = window.innerWidth
  if (width < 768) {
    // Mobile
    return { x: 2, y: 0, z: -0.5 }
  } else if (width < 1024) {
    // Tablet
    return { x: 2.8, y: 0, z: -0.7 }
  } else {
    // Desktop
    return { x: 3.5, y: 0, z: -1 }
  }
}

export function Human(props) {
  const { 
    currentSection = 'hero', 
    sectionProgress = 0,
    walkSpeed = 0.5,
    waveSpeed = 0.5,
    lerpSpeed = 0.15
  } = props
  
  const group = useRef()
  
  // Use compressed version since human.bin file size (102KB) matches human-c.gltf's expected size (104KB)
  // The original human.gltf expects 1.4MB, causing the "Invalid typed array length: 117" error
  // Note: human-c.gltf uses meshopt compression - ensure your GLTF loader supports EXT_meshopt_compression
  const { scene, animations } = useGLTF('./models/human-c.gltf')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  
  // Bone references for procedural animation
  const bonesRef = useRef({
    head: null,
    neck: null,
    spine: null,
    hips: null,
    leftShoulder: null,
    rightShoulder: null,
    leftArm: null,
    rightArm: null,
    leftForearm: null,
    rightForearm: null,
    leftHand: null,
    rightHand: null,
    leftThigh: null,
    rightThigh: null,
    leftCalf: null,
    rightCalf: null,
    leftFoot: null,
    rightFoot: null,
  })

  // Animation state
  const [initialPosition] = useState({ x: 0, y: 0, z: 0 })
  const [targetWallPosition] = useState(getTargetPosition())
  const animationTimeRef = useRef(0)
  const bonesExtractedRef = useRef(false)
  const shouldStandUpRef = useRef(false)
  
  // Manually create animation mixer for the cloned scene (for standing up animation)
  const mixer = useMemo(() => {
    if (clone) {
      return new THREE.AnimationMixer(clone)
    }
    return null
  }, [clone])

  // Create actions from animations (standing up animation)
  const actions = useMemo(() => {
    if (!mixer || !animations || animations.length === 0) return {}
    
    const actionsMap = {}
    animations.forEach((clip) => {
      const action = mixer.clipAction(clip)
      actionsMap[clip.name] = action
    })
    return actionsMap
  }, [mixer, animations])

  // Store action ref to avoid dependency on actions object
  const standingActionRef = useRef(null)
  useEffect(() => {
    if (actions && Object.keys(actions).length > 0 && !standingActionRef.current) {
      standingActionRef.current = actions[Object.keys(actions)[0]]
    }
  }, [actions])

  // Extract bone references from skeleton
  useEffect(() => {
    if (nodes._rootJoint && !bonesExtractedRef.current) {
      nodes._rootJoint.traverse((bone) => {
        const name = bone.name.toLowerCase()
        
        // Head and neck
        if (name.includes(' ') && !name.includes('toe')) {
          bonesRef.current.head = bone
        }
        if (name.includes('neck')) {
          bonesRef.current.neck = bone
        }
        
        // Spine and hips
        if (name.includes('spine') && !name.includes('shoulder')) {
          bonesRef.current.spine = bone
        }
        if (name.includes('hip') || name.includes('pelvis')) {
          bonesRef.current.hips = bone
        }
        
        // Arms - Left
        if (name.includes('shoulder') && name.includes('l')) {
          bonesRef.current.leftShoulder = bone
        }
        if ((name.includes('upperarm') || name.includes('arm')) && name.includes('l') && !name.includes('forearm')) {
          bonesRef.current.leftArm = bone
        }
        if (name.includes('forearm') && name.includes('l')) {
          bonesRef.current.leftForearm = bone
        }
        if (name.includes('hand') && name.includes('l')) {
          bonesRef.current.leftHand = bone
        }
        
        // Arms - Right
        if (name.includes('shoulder') && name.includes('r')) {
          bonesRef.current.rightShoulder = bone
        }
        if ((name.includes('upperarm') || name.includes('arm')) && name.includes('r') && !name.includes('forearm')) {
          bonesRef.current.rightArm = bone
        }
        if (name.includes('forearm') && name.includes('r')) {
          bonesRef.current.rightForearm = bone
        }
        if (name.includes('hand') && name.includes('r')) {
          bonesRef.current.rightHand = bone
        }
        
        // Legs - Left
        if ((name.includes('thigh') || name.includes('upleg')) && name.includes('l')) {
          bonesRef.current.leftThigh = bone
        }
        if ((name.includes('calf') || name.includes('leg')) && name.includes('l') && !name.includes('upleg')) {
          bonesRef.current.leftCalf = bone
        }
        if (name.includes('foot') && name.includes('l') && !name.includes('toe')) {
          bonesRef.current.leftFoot = bone
        }
        
        // Legs - Right
        if ((name.includes('thigh') || name.includes('upleg')) && name.includes('r')) {
          bonesRef.current.rightThigh = bone
        }
        if ((name.includes('calf') || name.includes('leg')) && name.includes('r') && !name.includes('upleg')) {
          bonesRef.current.rightCalf = bone
        }
        if (name.includes('foot') && name.includes('r') && !name.includes('toe')) {
          bonesRef.current.rightFoot = bone
        }
      })
      bonesExtractedRef.current = true
    }
  }, [nodes])

  // Play standing up animation initially
  useEffect(() => {
    console.log('props.shouldStandUp', props.shouldStandUp, standingActionRef.current, shouldStandUpRef.current)
    if (props.shouldStandUp && standingActionRef.current ) {
      const action = standingActionRef.current
      shouldStandUpRef.current = true
      action.reset()
      action.setLoop(THREE.LoopOnce, 1)
      action.clampWhenFinished = true
      action.play()
    }
  }, [props.shouldStandUp])

  // Update mixer for standing animation
  useFrame((state, delta) => {
    if (mixer) {
      mixer.update(delta)
    }
    
    // Only apply procedural animations when in About section
    if (currentSection !== 'about') {
      animationTimeRef.current = 0
      return
    }
    
    // Increment animation time for walking cycle
    animationTimeRef.current += delta
    const time = animationTimeRef.current
    
    const progress = clamp(sectionProgress, 0, 1)
    
    // Animation stages based on scroll progress
    // 0.0 - 0.2: Look up (head lift) with smile
    // 0.2 - 0.4: Wave greeting with personality
    // 0.4 - 1.0: Natural walk to wall
    
    // === IDLE BREATHING ANIMATION (always active) ===
    const breathe = Math.sin(time * 1.5) * 0.02
    if (bonesRef.current.spine) {
      bonesRef.current.spine.rotation.x = breathe
    }
    
    // === HEAD LIFT ANIMATION (0.0 - 0.2) - More natural ===
    const headLiftProgress = clamp((progress - 0.0) / 0.2, 0, 1)
    const easedHeadLift = easeInOutCubic(headLiftProgress)
    
    if (bonesRef.current.neck) {
      // Natural head tilt with slight anticipation
      const anticipation = Math.sin(easedHeadLift * Math.PI) * 0.05
      const neckRotation = easedHeadLift * 0.4 + anticipation
      bonesRef.current.neck.rotation.x = lerp(bonesRef.current.neck.rotation.x, neckRotation, lerpSpeed)
      // Slight head turn towards camera
      bonesRef.current.neck.rotation.y = lerp(bonesRef.current.neck.rotation.y, easedHeadLift * 0.1, lerpSpeed * 0.67)
    }
    
    if (bonesRef.current.head) {
      const headRotation = easedHeadLift * 0.2
      bonesRef.current.head.rotation.x = lerp(bonesRef.current.head.rotation.x, headRotation, lerpSpeed)
      // Micro head movements for life
      const microMove = Math.sin(time * 3) * 0.01 * easedHeadLift
      bonesRef.current.head.rotation.z = microMove
    }
    
    // === WAVE ANIMATION (0.2 - 0.4) - More expressive and friendly ===
    const waveProgress = clamp((progress - 0.2) / 0.2, 0, 1)
    const easedWave = easeInOutCubic(waveProgress)
    
    if (bonesRef.current.rightShoulder || bonesRef.current.rightArm) {
      const shoulderBone = bonesRef.current.rightShoulder || bonesRef.current.rightArm
      
      // Natural arm raise with anticipation
      const raiseProgress = Math.min(easedWave * 1.5, 1)
      const armRaiseZ = raiseProgress * -1.8 // Raise arm higher
      const armRaiseX = raiseProgress * 0.5 // Slight forward movement
      const armRaiseY = raiseProgress * 0.3 // Slight outward rotation
      
      shoulderBone.rotation.z = lerp(shoulderBone.rotation.z, armRaiseZ, lerpSpeed)
      shoulderBone.rotation.x = lerp(shoulderBone.rotation.x, armRaiseX, lerpSpeed)
      shoulderBone.rotation.y = lerp(shoulderBone.rotation.y, armRaiseY, lerpSpeed)
    }
    
    if (bonesRef.current.rightForearm && waveProgress > 0) {
      // Enthusiastic wave motion with natural rhythm
      const waveSpeedValue = 6.5 * waveSpeed
      const waveTime = time * waveSpeedValue
      const waveAmount = Math.sin(waveTime) * 0.6
      const waveIntensity = Math.min(easedWave * 2, 1) * (1 - Math.max((progress - 0.4) / 0.1, 0))
      
      // Natural wrist rotation
      bonesRef.current.rightForearm.rotation.y = waveAmount * waveIntensity
      bonesRef.current.rightForearm.rotation.z = lerp(bonesRef.current.rightForearm.rotation.z, -0.7 * waveIntensity, lerpSpeed)
      
      // Add slight up-down motion for more life
      const upDown = Math.sin(waveTime * 0.5) * 0.1 * waveIntensity
      bonesRef.current.rightForearm.rotation.x = upDown
    }
    
    // Body leans slightly during wave
    if (bonesRef.current.spine && waveProgress > 0 && waveProgress < 1) {
      const leanAmount = Math.sin(easedWave * Math.PI) * 0.08
      bonesRef.current.spine.rotation.z = lerp(bonesRef.current.spine.rotation.z, -leanAmount, lerpSpeed * 0.67)
    }
    
    // === REALISTIC WALKING ANIMATION (0.4 - 1.0) ===
    const walkProgress = clamp((progress - 0.4) / 0.6, 0, 1)
    const easedWalk = easeInOutCubic(walkProgress)
    
    if (walkProgress > 0 && group.current) {
      // Move character position with smooth acceleration/deceleration
      const startPos = initialPosition
      const endPos = targetWallPosition
      
      group.current.position.x = lerp(startPos.x, endPos.x, easedWalk)
      group.current.position.z = lerp(startPos.z, endPos.z, easedWalk)
      
      // Natural body rotation to face direction
      const targetRotation = Math.atan2(endPos.x - startPos.x, endPos.z - startPos.z)
      group.current.rotation.y = lerp(group.current.rotation.y, targetRotation, lerpSpeed * 0.53)
      
      // === REALISTIC WALK CYCLE ===
      const walkCycleSpeedValue = 5.5 * walkSpeed // Configurable walking pace
      const walkCycleTime = time * walkCycleSpeedValue
      const walkIntensity = Math.min(walkProgress * 2, 1) // Smooth start
      
      // Vertical body bob (natural walking bounce)
      const bobAmount = Math.abs(Math.sin(walkCycleTime * 2)) * 0.08 * walkIntensity
      if (group.current) {
        group.current.position.y = initialPosition.y + bobAmount
      }
      
      // === REALISTIC LEG MOTION ===
      // Left leg
      if (bonesRef.current.leftThigh) {
        const leftLegCycle = Math.sin(walkCycleTime)
        bonesRef.current.leftThigh.rotation.x = leftLegCycle * 0.8 * walkIntensity
        bonesRef.current.leftThigh.rotation.y = leftLegCycle * 0.05 * walkIntensity // Slight inward motion
      }
      
      if (bonesRef.current.leftCalf) {
        // Knee bends more when leg swings forward
        const leftKneeBend = Math.max(0, Math.sin(walkCycleTime - 0.3)) * 1.2
        bonesRef.current.leftCalf.rotation.x = leftKneeBend * walkIntensity
      }
      
      if (bonesRef.current.leftFoot) {
        // Foot naturally points down when lifted
        const footAngle = Math.sin(walkCycleTime) * 0.3
        bonesRef.current.leftFoot.rotation.x = Math.min(0, footAngle) * walkIntensity
      }
      
      // Right leg (opposite phase)
      if (bonesRef.current.rightThigh) {
        const rightLegCycle = Math.sin(walkCycleTime + Math.PI)
        bonesRef.current.rightThigh.rotation.x = rightLegCycle * 0.8 * walkIntensity
        bonesRef.current.rightThigh.rotation.y = rightLegCycle * 0.05 * walkIntensity
      }
      
      if (bonesRef.current.rightCalf) {
        const rightKneeBend = Math.max(0, Math.sin(walkCycleTime + Math.PI - 0.3)) * 1.2
        bonesRef.current.rightCalf.rotation.x = rightKneeBend * walkIntensity
      }
      
      if (bonesRef.current.rightFoot) {
        const footAngle = Math.sin(walkCycleTime + Math.PI) * 0.3
        bonesRef.current.rightFoot.rotation.x = Math.min(0, footAngle) * walkIntensity
      }
      
      // === REALISTIC ARM SWING ===
      // Only swing arms after wave is complete
      const armSwingReady = Math.min((progress - 0.42) / 0.05, 1)
      
      if (armSwingReady > 0) {
        // Left arm (opposite to right leg)
        if (bonesRef.current.leftShoulder || bonesRef.current.leftArm) {
          const leftArmBone = bonesRef.current.leftShoulder || bonesRef.current.leftArm
          const leftSwing = Math.sin(walkCycleTime + Math.PI) * 0.5
          leftArmBone.rotation.x = lerp(leftArmBone.rotation.x, leftSwing * walkIntensity * armSwingReady, lerpSpeed)
          leftArmBone.rotation.z = lerp(leftArmBone.rotation.z, 0.1 * walkIntensity, lerpSpeed * 0.67)
        }
        
        // Right arm (opposite to left leg)
        if (bonesRef.current.rightShoulder || bonesRef.current.rightArm) {
          const rightArmBone = bonesRef.current.rightShoulder || bonesRef.current.rightArm
          const rightSwing = Math.sin(walkCycleTime) * 0.5
          
          // Smoothly return from wave pose
          rightArmBone.rotation.x = lerp(rightArmBone.rotation.x, rightSwing * walkIntensity * armSwingReady, lerpSpeed)
          rightArmBone.rotation.z = lerp(rightArmBone.rotation.z, 0.1 * walkIntensity, lerpSpeed)
          rightArmBone.rotation.y = lerp(rightArmBone.rotation.y, 0, lerpSpeed * 0.67)
        }
        
        // Forearms have natural bend
        if (bonesRef.current.rightForearm) {
          bonesRef.current.rightForearm.rotation.z = lerp(bonesRef.current.rightForearm.rotation.z, -0.2 * walkIntensity, lerpSpeed)
          bonesRef.current.rightForearm.rotation.y = lerp(bonesRef.current.rightForearm.rotation.y, 0, lerpSpeed)
          bonesRef.current.rightForearm.rotation.x = lerp(bonesRef.current.rightForearm.rotation.x, 0, lerpSpeed)
        }
        
        if (bonesRef.current.leftForearm) {
          bonesRef.current.leftForearm.rotation.z = lerp(bonesRef.current.leftForearm.rotation.z, 0.2 * walkIntensity, lerpSpeed)
        }
      }
      
      // === HIP AND SPINE MOTION (weight transfer) ===
      if (bonesRef.current.hips) {
        // Hips rotate with steps (natural weight shift)
        const hipRotation = Math.sin(walkCycleTime) * 0.15 * walkIntensity
        bonesRef.current.hips.rotation.y = lerp(bonesRef.current.hips.rotation.y, hipRotation, lerpSpeed)
        
        // Hips tilt side to side (weight on supporting leg)
        const hipTilt = Math.sin(walkCycleTime * 2) * 0.08 * walkIntensity
        bonesRef.current.hips.rotation.z = lerp(bonesRef.current.hips.rotation.z, hipTilt, lerpSpeed)
        
        // Slight forward lean when walking
        bonesRef.current.hips.rotation.x = lerp(bonesRef.current.hips.rotation.x, -0.05 * walkIntensity, lerpSpeed * 0.67)
      }
      
      if (bonesRef.current.spine) {
        // Counter-rotate spine for natural torso twist
        const spineRotation = Math.sin(walkCycleTime) * -0.08 * walkIntensity
        bonesRef.current.spine.rotation.y = lerp(bonesRef.current.spine.rotation.y, spineRotation, lerpSpeed)
        
        // Return spine lean to neutral
        bonesRef.current.spine.rotation.z = lerp(bonesRef.current.spine.rotation.z, 0, lerpSpeed * 0.67)
      }
      
      // === HEAD MOVEMENT (follows body motion naturally) ===
      if (bonesRef.current.head && walkProgress > 0.1) {
        // Head stays relatively stable (compensates for body motion)
        const headStabilize = Math.sin(walkCycleTime) * 0.03 * walkIntensity
        bonesRef.current.head.rotation.y = lerp(bonesRef.current.head.rotation.y, -headStabilize, lerpSpeed * 0.67)
        
        // Slight head bob
        const headBob = Math.sin(walkCycleTime * 2) * 0.02 * walkIntensity
        bonesRef.current.head.rotation.x = lerp(bonesRef.current.head.rotation.x, 0.1 + headBob, lerpSpeed * 0.67)
      }
    } else {
      // === IDLE POSE (when not walking) ===
      // Gradually return all bones to neutral/rest position
      if (bonesRef.current.spine) {
        bonesRef.current.spine.rotation.y = lerp(bonesRef.current.spine.rotation.y, 0, lerpSpeed * 0.33)
        bonesRef.current.spine.rotation.z = lerp(bonesRef.current.spine.rotation.z, 0, lerpSpeed * 0.33)
      }
      
      if (bonesRef.current.hips) {
        bonesRef.current.hips.rotation.x = lerp(bonesRef.current.hips.rotation.x, 0, lerpSpeed * 0.33)
        bonesRef.current.hips.rotation.y = lerp(bonesRef.current.hips.rotation.y, 0, lerpSpeed * 0.33)
        bonesRef.current.hips.rotation.z = lerp(bonesRef.current.hips.rotation.z, 0, lerpSpeed * 0.33)
      }
    }
  })

  return (
    <group ref={group} {...props} dispose={null} name="Human" >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="a317dc88ec0043219d58cd8b06b6ff60fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Sit_Arm" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_31">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_254" position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_255" geometry={nodes.Object_255.geometry} material={materials['Material.005']} skeleton={nodes.Object_255.skeleton} />
                  </group>
                </group>
                <group name="cs_grp" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="cs_master" position={[0.5, 0, 17.5]} scale={0.1} />
                  <group name="cs_square_2" position={[0.5, 0, 1.497]} rotation={[-Math.PI, 0, 0]} scale={0.154} />
                  <group name="cs_square" position={[1.5, 0, 1.497]} rotation={[-Math.PI, 0, 0]} scale={0.154} />
                  <group name="cs_hips" position={[0.5, 0, 11.5]} scale={0.206} />
                  <group name="cs_circle" position={[0.5, 0, 4.5]} scale={0.206} />
                  <group name="cs_neck" position={[0.5, 0, 14.5]} scale={0.206} />
                  <group name="cs_head" position={[0.5, 0, 13.5]} scale={0.206} />
                  <group name="cs_shoulder_left" position={[0.5, 0, 15.5]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={1.038} />
                  <group name="cs_arm_fk" position={[1.5, 0, 8.5]} scale={0.822} />
                  <group name="cs_forearm_fk" position={[2.5, 0, 8.5]} scale={0.822} />
                  <group name="cs_sphere_012" position={[3.5, 0, 2.5]} scale={0.206} />
                  <group name="cs_sphere" position={[0.5, 0, 2.5]} scale={0.206} />
                  <group name="cs_hand" position={[0.5, 0, 19.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_circle_025" position={[2.5, 0, 4.5]} scale={0.206} />
                  <group name="cs_circle001" position={[0.5, 0, 4.5]} scale={0.206} />
                  <group name="cs_shoulder_right" position={[0.5, 0, 16.5]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={1.038} />
                  <group name="cs_thigh_fk" position={[0.5, 0, 7.5]} scale={0.822} />
                  <group name="cs_calf_fk" position={[0.5, 0, 8.5]} scale={0.822} />
                  <group name="cs_foot" position={[0.5, 0, 10.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_foot_roll" position={[0.5, 0, 12.5]} scale={0.592} />
                  <group name="cs_foot001" position={[0.5, 0, 10.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_foot_01" position={[0.5, 0, 18.5]} rotation={[0, 0, Math.PI / 2]} scale={2.186} />
                  <group name="cs_foot002" position={[0.5, 0, 10.5]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
                  <group name="cs_toe" position={[0.5, 0, 9.5]} scale={0.429} />
                  <group name="cs_user_Ctrl_Hand_IK_Right" position={[-0.195, -0.284, 0.646]} rotation={[2.998, 0.011, -0.867]} scale={0.096} />
                </group>
                <group name="meHumanMale001" position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

// Preload the compressed version (matches the actual binary file size)
useGLTF.preload('./models/human-c.gltf')
