/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new-rob.gltf 
*/

import React, { useEffect, useRef } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function NewRob(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/new-rob.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, mixer } = useAnimations(animations, group)
  const currentAnimationIndex = useRef(0)
  const currentAction = useRef(null)
  const animationNames = useRef([])
  const actionsRef = useRef(null)
  const transitionDelay = useRef(0)
  const hasFinished = useRef(false)

  // Store actions in ref for useFrame access
  useEffect(() => {
    actionsRef.current = actions
  }, [actions])

  // Initialize animations
  useEffect(() => {
    if (!actions || Object.keys(actions).length === 0) return

    animationNames.current = Object.keys(actions)
    if (animationNames.current.length === 0) return

    // Start with first animation
    const firstAnimationName = animationNames.current[0]
    const firstAction = actions[firstAnimationName]
    
    if (firstAction) {
      currentAction.current = firstAction
      firstAction.reset()
      firstAction.setLoop(0, 1) // Play once (no loop)
      firstAction.clampWhenFinished = true
      firstAction.play()
    }
  }, [actions])

  // Update mixer and check animation completion
  useFrame((state, delta) => {
    if (mixer) {
      mixer.update(delta)
    }

    // Check if current animation has finished
    if (currentAction.current && animationNames.current.length > 0 && actionsRef.current) {
      const action = currentAction.current
      const clip = action.getClip()
      
      // Check if animation has finished (time >= duration)
      if (action.time >= clip.duration && !hasFinished.current) {
        // Mark as finished and start transition delay
        hasFinished.current = true
        transitionDelay.current = 0.5 // 500ms delay
      }
      
      // Handle transition delay
      if (hasFinished.current && transitionDelay.current > 0) {
        transitionDelay.current -= delta
        
        if (transitionDelay.current <= 0) {
          // Move to next animation
          currentAnimationIndex.current = (currentAnimationIndex.current + 1) % animationNames.current.length
          const nextAnimationName = animationNames.current[currentAnimationIndex.current]
          const nextAction = actionsRef.current[nextAnimationName]
          
          if (nextAction) {
            // Stop current action
            action.stop()
            
            // Reset and play next action
            currentAction.current = nextAction
            nextAction.reset()
            nextAction.setLoop(0, 1) // Play once (no loop)
            nextAction.clampWhenFinished = true
            nextAction.play()
            
            // Reset flags for next animation
            transitionDelay.current = 0
            hasFinished.current = false
          }
        }
      }
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Meshy_Walking_Armature" scale={0.01}>
          <primitive object={nodes.Hips} />
          <skinnedMesh name="char1" geometry={nodes.char1.geometry} material={materials['Material_1.001']} skeleton={nodes.char1.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/new-rob.gltf')
